INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('1', 'Israel', '+972', 'IL');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('2', 'Afghanistan', '+93', 'AF');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('3', 'Albania', '+355', 'AL');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('4', 'Algeria', '+213', 'DZ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('5', 'AmericanSamoa', '+1684', 'AS');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('6', 'Andorra', '+376', 'AD');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('7', 'Angola', '+244', 'AO');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('8', 'Anguilla', '+1264', 'AI');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('9', 'Antigua and Barbuda', '+1268', 'AG');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('10', 'Argentina', '+54', 'AR');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('11', 'Armenia', '+374', 'AM');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('12', 'Aruba', '+297', 'AW');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('13', 'Australia', '+61', 'AU');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('14', 'Austria', '+43', 'AT');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('15', 'Azerbaijan', '+994', 'AZ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('16', 'Bahamas', '+1242', 'BS');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('17', 'Bahrain', '+973', 'BH');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('18', 'Bangladesh', '+880', 'BD');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('19', 'Barbados', '+1246', 'BB');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('20', 'Belarus', '+375', 'BY');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('21', 'Belgium', '+32', 'BE');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('22', 'Belize', '+501', 'BZ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('23', 'Benin', '+229', 'BJ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('24', 'Bermuda', '+1441', 'BM');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('25', 'Bhutan', '+975', 'BT');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('26', 'Bosnia and Herzegovina', '+387', 'BA');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('27', 'Botswana', '+267', 'BW');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('28', 'Brazil', '+55', 'BR');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('29', 'British Indian Ocean Territory', '+246', 'IO');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('30', 'Bulgaria', '+359', 'BG');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('31', 'Burkina Faso', '+226', 'BF');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('32', 'Burundi', '+257', 'BI');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('33', 'Cambodia', '+855', 'KH');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('34', 'Cameroon', '+237', 'CM');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('35', 'Canada', '+1', 'CA');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('36', 'Cape Verde', '+238', 'CV');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('37', 'Cayman Islands', '+345', 'KY');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('38', 'Central African Republic', '+236', 'CF');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('39', 'Chad', '+235', 'TD');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('40', 'Chile', '+56', 'CL');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('41', 'China', '+86', 'CN');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('42', 'Christmas Island', '+61', 'CX');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('43', 'Colombia', '+57', 'CO');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('44', 'Comoros', '+269', 'KM');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('45', 'Congo', '+242', 'CG');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('46', 'Cook Islands', '+682', 'CK');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('47', 'Costa Rica', '+506', 'CR');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('48', 'Croatia', '+385', 'HR');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('49', 'Cuba', '+53', 'CU');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('50', 'Cyprus', '+537', 'CY');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('51', 'Czech Republic', '+420', 'CZ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('52', 'Denmark', '+45', 'DK');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('53', 'Djibouti', '+253', 'DJ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('54', 'Dominica', '+1767', 'DM');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('55', 'Dominican Republic', '+1849', 'DO');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('56', 'Ecuador', '+593', 'EC');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('57', 'Egypt', '+20', 'EG');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('58', 'El Salvador', '+503', 'SV');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('59', 'Equatorial Guinea', '+240', 'GQ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('60', 'Eritrea', '+291', 'ER');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('61', 'Estonia', '+372', 'EE');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('62', 'Ethiopia', '+251', 'ET');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('63', 'Faroe Islands', '+298', 'FO');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('64', 'Fiji', '+679', 'FJ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('65', 'Finland', '+358', 'FI');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('66', 'France', '+33', 'FR');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('67', 'French Guiana', '+594', 'GF');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('68', 'French Polynesia', '+689', 'PF');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('69', 'Gabon', '+241', 'GA');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('70', 'Gambia', '+220', 'GM');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('71', 'Georgia', '+995', 'GE');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('72', 'Germany', '+49', 'DE');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('73', 'Ghana', '+233', 'GH');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('74', 'Gibraltar', '+350', 'GI');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('75', 'Greece', '+30', 'GR');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('76', 'Greenland', '+299', 'GL');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('77', 'Grenada', '+1473', 'GD');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('78', 'Guadeloupe', '+590', 'GP');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('79', 'Guam', '+1671', 'GU');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('80', 'Guatemala', '+502', 'GT');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('81', 'Guinea', '+224', 'GN');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('82', 'Guinea-Bissau', '+245', 'GW');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('83', 'Guyana', '+595', 'GY');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('84', 'Haiti', '+509', 'HT');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('85', 'Honduras', '+504', 'HN');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('86', 'Hungary', '+36', 'HU');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('87', 'Iceland', '+354', 'IS');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('88', 'India', '+91', 'IN');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('89', 'Indonesia', '+62', 'ID');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('90', 'Iraq', '+964', 'IQ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('91', 'Ireland', '+353', 'IE');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('92', 'Israel', '+972', 'IL');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('93', 'Italy', '+39', 'IT');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('94', 'Jamaica', '+1876', 'JM');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('95', 'Japan', '+81', 'JP');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('96', 'Jordan', '+962', 'JO');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('97', 'Kazakhstan', '+77', 'KZ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('98', 'Kenya', '+254', 'KE');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('99', 'Kiribati', '+686', 'KI');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('100', 'Kuwait', '+965', 'KW');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('101', 'Kyrgyzstan', '+996', 'KG');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('102', 'Latvia', '+371', 'LV');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('103', 'Lebanon', '+961', 'LB');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('104', 'Lesotho', '+266', 'LS');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('105', 'Liberia', '+231', 'LR');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('106', 'Liechtenstein', '+423', 'LI');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('107', 'Lithuania', '+370', 'LT');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('108', 'Luxembourg', '+352', 'LU');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('109', 'Madagascar', '+261', 'MG');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('110', 'Malawi', '+265', 'MW');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('111', 'Malaysia', '+60', 'MY');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('112', 'Maldives', '+960', 'MV');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('113', 'Mali', '+223', 'ML');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('114', 'Malta', '+356', 'MT');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('115', 'Marshall Islands', '+692', 'MH');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('116', 'Martinique', '+596', 'MQ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('117', 'Mauritania', '+222', 'MR');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('118', 'Mauritius', '+230', 'MU');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('119', 'Mayotte', '+262', 'YT');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('120', 'Mexico', '+52', 'MX');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('121', 'Monaco', '+377', 'MC');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('122', 'Mongolia', '+976', 'MN');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('123', 'Montenegro', '+382', 'ME');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('124', 'Montserrat', '+1664', 'MS');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('125', 'Morocco', '+212', 'MA');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('126', 'Myanmar', '+95', 'MM');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('127', 'Namibia', '+264', 'NA');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('128', 'Nauru', '+674', 'NR');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('129', 'Nepal', '+977', 'NP');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('130', 'Netherlands', '+31', 'NL');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('131', 'Netherlands Antilles', '+599', 'AN');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('132', 'New Caledonia', '+687', 'NC');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('133', 'New Zealand', '+64', 'NZ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('134', 'Nicaragua', '+505', 'NI');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('135', 'Niger', '+227', 'NE');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('136', 'Nigeria', '+234', 'NG');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('137', 'Niue', '+683', 'NU');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('138', 'Norfolk Island', '+672', 'NF');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('139', 'Northern Mariana Islands', '+1670', 'MP');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('140', 'Norway', '+47', 'NO');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('141', 'Oman', '+968', 'OM');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('142', 'Pakistan', '+92', 'PK');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('143', 'Palau', '+680', 'PW');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('144', 'Panama', '+507', 'PA');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('145', 'Papua New Guinea', '+675', 'PG');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('146', 'Paraguay', '+595', 'PY');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('147', 'Peru', '+51', 'PE');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('148', 'Philippines', '+63', 'PH');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('149', 'Poland', '+48', 'PL');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('150', 'Portugal', '+351', 'PT');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('151', 'Puerto Rico', '+1939', 'PR');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('152', 'Qatar', '+974', 'QA');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('153', 'Romania', '+40', 'RO');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('154', 'Rwanda', '+250', 'RW');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('155', 'Samoa', '+685', 'WS');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('156', 'San Marino', '+378', 'SM');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('157', 'Saudi Arabia', '+966', 'SA');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('158', 'Senegal', '+221', 'SN');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('159', 'Serbia', '+381', 'RS');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('160', 'Seychelles', '+248', 'SC');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('161', 'Sierra Leone', '+232', 'SL');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('162', 'Singapore', '+65', 'SG');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('163', 'Slovakia', '+421', 'SK');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('164', 'Slovenia', '+386', 'SI');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('165', 'Solomon Islands', '+677', 'SB');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('166', 'South Africa', '+27', 'ZA');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('167', 'South Georgia and the South Sandwich Islands', '+500', 'GS');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('168', 'Spain', '+34', 'ES');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('169', 'Sri Lanka', '+94', 'LK');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('170', 'Sudan', '+249', 'SD');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('171', 'Suriname', '+597', 'SR');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('172', 'Swaziland', '+268', 'SZ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('173', 'Sweden', '+46', 'SE');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('174', 'Switzerland', '+41', 'CH');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('175', 'Tajikistan', '+992', 'TJ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('176', 'Thailand', '+66', 'TH');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('177', 'Togo', '+228', 'TG');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('178', 'Tokelau', '+690', 'TK');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('179', 'Tonga', '+676', 'TO');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('180', 'Trinidad and Tobago', '+1868', 'TT');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('181', 'Tunisia', '+216', 'TN');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('182', 'Turkey', '+90', 'TR');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('183', 'Turkmenistan', '+993', 'TM');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('184', 'Turks and Caicos Islands', '+1649', 'TC');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('185', 'Tuvalu', '+688', 'TV');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('186', 'Uganda', '+256', 'UG');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('187', 'Ukraine', '+380', 'UA');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('188', 'United Arab Emirates', '+971', 'AE');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('189', 'United Kingdom', '+44', 'GB');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('190', 'United States', '+1', 'US');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('191', 'Uruguay', '+598', 'UY');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('192', 'Uzbekistan', '+998', 'UZ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('193', 'Vanuatu', '+678', 'VU');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('194', 'Wallis and Futuna', '+681', 'WF');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('195', 'Yemen', '+967', 'YE');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('196', 'Zambia', '+260', 'ZM');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('197', 'Zimbabwe', '+263', 'ZW');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `code`) VALUES ('198', 'land Islands', 'AX');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `code`) VALUES ('199', 'Antarctica', 'AQ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('200', 'Bolivia, Plurinational State of', '+591', 'BO');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('201', 'Brunei Darussalam', '+673', 'BN');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('202', 'Cocos (Keeling) Islands', '+61', 'CC');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('203', 'Congo, The Democratic Republic of the', '+243', 'CD');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('204', 'Cote d\'Ivoire', '+225', 'CI');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('205', 'Falkland Islands (Malvinas)', '+500', 'FK');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('206', 'Guernsey', '+44', 'GG');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('207', 'Holy See (Vatican City State)', '+379', 'VA');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('208', 'Hong Kong', '+852', 'HK');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('209', 'Iran, Islamic Republic of', '+98', 'IR');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('210', 'Isle of Man', '+44', 'IM');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('211', 'Jersey', '+44', 'JE');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('212', 'Korea, Democratic People\'s Republic of', '+850', 'KP');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('213', 'Korea, Republic of', '+82', 'KR');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('214', 'Lao People\'s Democratic Republic', '+856', 'LA');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('215', 'Libyan Arab Jamahiriya', '+218', 'LY');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('216', 'Macao', '+853', 'MO');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('217', 'Macedonia, The Former Yugoslav Republic of', '+389', 'MK');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('218', 'Micronesia, Federated States of', '+691', 'FM');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('219', 'Moldova, Republic of', '+373', 'MD');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('220', 'Mozambique', '+258', 'MZ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('221', 'Palestinian Territory, Occupied', '+970', 'PS');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('222', 'Pitcairn', '+872', 'PN');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('223', 'Réunion', '+262', 'RE');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('224', 'Russia', '+7', 'RU');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('225', 'Saint Barthélemy', '+590', 'BL');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('226', 'Saint Helena, Ascension and Tristan Da Cunha', '+290', 'SH');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('227', 'Saint Kitts and Nevis', '+1869', 'KN');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('228', 'Saint Lucia', '+1758', 'LC');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('229', 'Saint Martin', '+590', 'MF');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('230', 'Saint Pierre and Miquelon', '+508', 'PM');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('231', 'Saint Vincent and the Grenadines', '+1784', 'VC');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('232', 'Sao Tome and Principe', '+239', 'ST');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('233', 'Somalia', '+252', 'SO');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('234', 'Svalbard and Jan Mayen', '+47', 'SJ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('235', 'Syrian Arab Republic', '+963', 'SY');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('236', 'Taiwan, Province of China', '+886', 'TW');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('237', 'Tanzania, United Republic of', '+255', 'TZ');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('238', 'Timor-Leste', '+670', 'TL');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('239', 'Venezuela, Bolivarian Republic of', '+58', 'VE');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('240', 'Viet Nam', '+84', 'VN');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('241', 'Virgin Islands, British', '+1284', 'VG');
INSERT INTO `manoapp`.`countries` (`id`, `name`, `dialCode`, `code`) VALUES ('242', 'Virgin Islands, U.S.', '+1340', 'VI');
